Switch to Github Actions
phpspec/prophecy pull request #515
Opened 2020-12-17 10:40 UTC by ciaranmcnulty

2020-12-17 13:27 UTC, stof requested changes

2020-12-17 13:27 UTC, stof commented on .github/workflows/build.yml
> +      -   name: Install dependencies
to run both phpspec and phpunit even when phpspec fails (as done on Travis currently), here is the way to go:

```
-   name: Install dependencies
    run: COMPOSER_ROOT_VERSION=dev-master composer update ${{ matrix.composer-flags }}
    id: end-of-setup

-   name: Run tests (phpspec)
    run: bin/phpspec run --format=dot
    if: always() && end-of-setup.outcome == 'success'

-   name: Run tests (phpunit)
    run: ./vendor/bin/phpunit
    if: always() && end-of-setup.outcome == 'success'
```

2020-12-17 13:27 UTC, stof commented on .github/workflows/build.yml
> +          run: bin/phpspec run --format=dot
must be `vendor/bin/phpspec`

2020-12-18 09:04 UTC, jakzal commented on .github/workflows/build.yml
> +            php-version: "${{ matrix.php }}"
If you don't need coverage it can [be disabled](https://github.com/marketplace/actions/setup-php-action#disable-coverage) with `coverage: none`. This way xdebug won't affect performance of test runs.

2020-12-19 09:31 UTC, ciaranmcnulty commented on .github/workflows/build.yml
> +      -   name: Install dependencies
Will this still fail the build if one fails?

2020-12-19 09:54 UTC, merged