Support standalone and nullable types for true, false, and null.
phpspec/prophecy pull request #566
Opened 2022-09-11 18:23 UTC by kschatzle

2022-09-17 07:46 UTC, stof requested changes

2022-09-17 07:46 UTC, stof commented on src/Prophecy/Doubler/Generator/Node/TypeNodeAbstract.php
> +            case 'true':
true is not a builtin type before PHP 8.2, so it should not be in this branch. It needs a version check, as done for `mixed`

2022-09-17 15:11 UTC, kschatzle commented
Question in general. Since true isn't a builtin type until PHP8.2, the code that is being mocked shouldn't have true as a standalone type. So how do choose what to prevent via versioning and what not?

2022-09-26 13:28 UTC, kschatzle commented on src/Prophecy/Doubler/Generator/Node/TypeNodeAbstract.php
> +            case 'true':
Done.

2022-11-29 14:08 UTC, ciaranmcnulty commented
@kschatzle not sure what the question means really? You have the PHP version checks in place that look correct, to me at least

Can you rebase please?

2022-11-29 14:39 UTC, ciaranmcnulty commented
ok I fixed the conflict and fixed an issue with true handling - thanks!

2022-11-29 14:39 UTC, merged